### ISSUE TITLE
Mini cart displaying 10 decimal places when added. 

### ISSUE THREAD

**Issue by a-support** [puikinsh/tyche#37]
The mini cart at the top is showing 10 decimals and the price excluding tax.
I’ve changed the WooCommerce setting to show only 2 decimals and that is working in the checkout.

Discussion:
 https://colorlib.com/wp/forums/topic/mini-cart-is-showing-10-decimals/#post-126948

**Comment by giucu91** [comment]
Hello @a-support ,

You can select how many decimals you want to have in WooCommerce -> Settings -> General under Number of decimals.

Regarding taxes, if you want the cart total to include taxes you will need to go to WooCommerce -> Settings -> Tax under **Prices entered with tax** select **Yes, I will enter prices inclusive of tax**. If you don't have this options checked it's not ok to include the tax in the total price because if someone will add to cart a product with 10$ price, the total will be 12$ and that is not ok.

**Comment by a-support** [comment]
Hello @giucu91,

I tested the solution and it works.
