### ISSUE TITLE
Space at the end of the products list in the shop

### ISSUE THREAD

**Issue by a-support** [puikinsh/tyche#39]
The shop has 2 - 3 empty item spaces at the end of the list of products .

Reference:
https://colorlib.com/wp/forums/topic/layout-problems/#post-133948

**Comment by giucu91** [comment]
Hello @a-support ,

A shop page by default has 3 columns and 12 products on the pages with sidebar and 4 columns and 12 products on full width pages . Users that chose to display only 10 products have this problem. So in order to solve it they will need to select from Customizer -> Theme Options -> WooCommerce how many products and columns they need to have on pages with sidebar and pages without sidebar.

Hope this makes sense, if not please don't hesitate to contact me for more clarifications

**Comment by a-support** [comment]
Hello @giucu91,

Thanks for sharing that information with me. I will keep it in mind next time.
