### ISSUE TITLE
Slider Text isn't translatable. 

### ISSUE THREAD

**Issue by a-support** [puikinsh/tyche#42]
This website here uses a language switcher,
Site: https://www.alexfocus.com/boutique/en/home_en/
Other texts are translated except that in the header. 
I tried localizing it but no luck. 

Discussion. 
https://colorlib.com/wp/forums/topic/problems-with-the-headers/#post-142806

**Comment by giucu91** [comment]
Hello @a-support ,

In order to translate this text the users will need to save their text( if they leave the default one will not work ) after that they need to go to Polylang -> String translations and select the tyche group.

Hope this makes sense, if not please don't hesitate to contact me for more clarifications.

**Comment by a-support** [comment]
Hello @giucu91 ,

This seems to work for the slider section information but not for the CTA used with the individual slider images.
