### ISSUE TITLE
Fatal error: Class 'Epsilon_Framework' not found

### ISSUE THREAD

**Issue by ASP-Akshay** [puikinsh/tyche#9]
Hey puikinsh.., 
I'm learner in WordPress. In this master theme file I can got a fatal error. 
Please say to me how can I solve this error. 

The error is... 
Fatal error: Class 'Epsilon_Framework' not found in C:\xampp\htdocs\wordpress\wp-content\themes\tyche\inc\class-tyche.php on line 87

**Comment by cristianraiber** [comment]
This is happening because you tried downloading Tyche from GitHub, by using GitHub Desktop Client. You can read more about this issue here: https://github.com/puikinsh/Activello#repository-clonedownload-fire-fire-fire 

Also, latest releases will always be available here: https://github.com/puikinsh/tyche/releases (zip format). 

Thanks.
